# Generated by Django 5.0.6 on 2024-05-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_professor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='title',
            field=models.CharField(blank=True, choices=[('ASST', 'Assistant Professor'), ('ASSOC', 'Associate Professor'), ('PROF', 'Professor'), ('LECT', 'Lecturer'), ('INST', 'Instructor'), ('CHAIR', 'Chairman')], max_length=5, null=True),
        ),
    ]
