# Generated by Django 5.0.6 on 2024-05-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_professor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default/default_image.png', null=True, upload_to='media/'),
        ),
    ]
