# Generated by Django 5.0.6 on 2024-05-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_chaired', to='users.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_courses',
            field=models.ManyToManyField(related_name='majors_core', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='required_courses',
            field=models.ManyToManyField(related_name='majors_required', to='courses.course'),
        ),
        migrations.AddField(
            model_name='minor',
            name='required_courses',
            field=models.ManyToManyField(related_name='minors_required', to='courses.course'),
        ),
    ]
