# Generated by Django 4.2.7 on 2024-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='website',
        ),
        migrations.AddField(
            model_name='major',
            name='core_additional_distribution',
            field=models.ManyToManyField(related_name='majors_core_additional_distribution', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_distribution',
            field=models.ManyToManyField(related_name='majors_core_distribution', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_seminars',
            field=models.ManyToManyField(related_name='majors_core_seminars', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_skills',
            field=models.ManyToManyField(related_name='majors_core_skills', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_writing_speaking_intensive',
            field=models.ManyToManyField(related_name='majors_core_writing_speaking_intensive', to='courses.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='program_requirements',
            field=models.ManyToManyField(related_name='majors_program_requirements', to='courses.course'),
        ),
    ]
