# Generated by Django 4.2.7 on 2024-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_major_image_minor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
