# Generated by Django 4.2.7 on 2024-05-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_attribute_majorattributerequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attributes',
            field=models.ManyToManyField(blank=True, choices=[('CNSL', 'Laboratory Science Requirement'), ('CNSN', 'Non-Laboratory or Laboratory Sciences Requirement'), ('CSOC', 'Social and Behavioral Sciences Requirement'), ('CFPA', 'Fine and Performing Arts Requirement'), ('CHUM', 'Humanities Requirement'), ('CGCL', 'Global Culture Requirement'), ('CMCL', 'Multiculturalism Requirement'), ('CUSC', 'United States and Massachusetts Constitutions Requirement'), ('CWRT', 'Writing Intensive Requirement'), ('CSPI', 'Speaking Intensive or Additional Writing Intensive Requirement'), ('CSPK', 'Intro to Public Speaking or Oral Interpretation')], to='courses.attribute'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
