# Generated by Django 4.2.7 on 2024-05-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_attributes_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='courses.attribute'),
        ),
    ]
