# Generated by Django 4.2.7 on 2024-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='description',
        ),
        migrations.AddField(
            model_name='attribute',
            name='code_name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
