# Generated by Django 5.0.6 on 2024-05-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_major_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department'),
        ),
    ]
