# Generated by Django 5.0.6 on 2024-05-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_department_eligibility_department_objectives_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentComment',
        ),
    ]
