# Generated by Django 5.0.6 on 2024-05-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_departmentcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentComment',
        ),
    ]
