# Generated by Django 5.0.6 on 2024-05-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_courseoutline_created_by'),
        ('users', '0009_person_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_comments', to='users.person'),
        ),
    ]
