# Generated by Django 4.2.7 on 2024-05-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_departmentreview_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOutline',
        ),
    ]
