# Generated by Django 4.2.7 on 2024-05-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_person_profile_pic'),
        ('courses', '0023_delete_courseoutline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_outlines', to='users.person')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outlines', to='courses.department')),
            ],
        ),
    ]
