# Generated by Django 4.2.7 on 2024-05-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseoutline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOutline',
        ),
    ]
